"""update user model for coordinates

Revision ID: 71f47a079739
Revises: 2c6e5616c811
Create Date: 2025-02-16 00:32:01.451585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71f47a079739'
down_revision: Union[str, None] = '2c6e5616c811'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('base_position_lat', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('base_position_lng', sa.Float(), nullable=True))
    op.drop_column('users', 'base_position')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('base_position', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'base_position_lng')
    op.drop_column('users', 'base_position_lat')
    # ### end Alembic commands ###
