"""create users table

Revision ID: 7b5c1e77f288
Revises: 
Create Date: 2025-02-15 00:23:00.039167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b5c1e77f288'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
        sa.Column('telegram_id', sa.Integer(), nullable=False),
        sa.Column('chat_id', sa.String(), nullable=False),
        sa.Column('avg_receipt', sa.Float(), nullable=True),
        sa.Column('preferences_by_type', sa.String(), nullable=True),
        sa.Column('preferences_by_food', sa.String(), nullable=True),
        sa.Column('base_position', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('telegram_id'),
        sa.UniqueConstraint('chat_id'),
        sa.UniqueConstraint('telegram_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
